### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by nf9k** [productiveops/dokemon#40]
I was updating a container-side volume path, in a pre-existing compose stack, to include a hidden directory.  Specifically, "/root/.jenkins"  Upon clicking save, dokemon's interface became unresponsive.  Further investigation showed dokemon endlessly restarting with the following error:

goroutine 6 [running]:
github.com/productiveops/dokemon/pkg/dockerapi.isContainerImageStale({0xc00003c0f0?, 0x23?}, {0xc000038050, 0x47}, 0x0?)
        /app/pkg/dockerapi/container_stale_check.go:33 +0x245
github.com/productiveops/dokemon/pkg/dockerapi.ContainerRefreshStaleStatus()
        /app/pkg/dockerapi/container_stale_check.go:75 +0x29d
github.com/productiveops/dokemon/pkg/dockerapi.ContainerScheduleRefreshStaleStatus()
        /app/pkg/dockerapi/container_stale_check.go:45 +0x15
created by github.com/productiveops/dokemon/pkg/server.NewServer in goroutine 1
        /app/pkg/server/server.go:86 +0x8a7
{"level":"info","level":"","time":"2024-10-18T03:52:17Z","message":"Setting log level"}
{"level":"info","time":"2024-10-18T03:52:17Z","message":"Starting Dokemon v1.5.9"}
{"level":"info","time":"2024-10-18T03:52:17Z","message":"Refreshing container stale status"}
⇨ http server started on [::]:9090
panic: runtime error: index out of range [0] with length 0

I'm assuming the . screwed something up.  The bummer is that dokemon is toast.  I'm assuming the change was committed to the db, which instantly broke things.  I've browsed around a bit in the DB, but I'm not a DBA, nor do I play one on TV.  I found the container record, but only located the previous version of the compose, which further confused me.

Let me know if I can provide further info.

**Comment by masterivanic** [comment]
@nf9k this was fixed in new version, check here https://github.com/dokemon-ng
